/**
 * GeoInsight — Dados Mock para Desenvolvimento
 * Dark Tech Sophisticated — Cyberpunk Minimalism
 * 
 * Dados de exemplo para testes quando a API está indisponível
 */

import { CountryData } from '@/types/countries';

export const mockCountries: CountryData[] = [
  {
    name: { common: 'Brazil', official: 'Federative Republic of Brazil' },
    cca2: 'BR',
    cca3: 'BRA',
    region: 'Americas',
    subregion: 'South America',
    capital: ['Brasília'],
    area: 8514877,
    population: 215313498,
    languages: { por: 'Portuguese' },
    currencies: { BRL: { name: 'Brazilian real', symbol: 'R$' } },
    flags: { svg: '🇧🇷' },
    latlng: [-14.235, -51.9253],
    timezones: ['UTC-05:00', 'UTC-04:00', 'UTC-03:00'],
    borders: ['BOL', 'COL', 'GUY', 'PER', 'SUR', 'URY', 'VEN'],
  },
  {
    name: { common: 'United States', official: 'United States of America' },
    cca2: 'US',
    cca3: 'USA',
    region: 'Americas',
    subregion: 'North America',
    capital: ['Washington, D.C.'],
    area: 9833520,
    population: 338289857,
    languages: { eng: 'English' },
    currencies: { USD: { name: 'United States dollar', symbol: '$' } },
    flags: { svg: '🇺🇸' },
    latlng: [37.0902, -95.7129],
    timezones: ['UTC-12:00', 'UTC-11:00', 'UTC-10:00', 'UTC-09:00', 'UTC-08:00', 'UTC-07:00', 'UTC-06:00', 'UTC-05:00'],
    borders: ['CAN', 'MEX'],
  },
  {
    name: { common: 'China', official: "People's Republic of China" },
    cca2: 'CN',
    cca3: 'CHN',
    region: 'Asia',
    subregion: 'Eastern Asia',
    capital: ['Beijing'],
    area: 9596961,
    population: 1425887337,
    languages: { zho: 'Chinese' },
    currencies: { CNY: { name: 'Chinese yuan', symbol: '¥' } },
    flags: { svg: '🇨🇳' },
    latlng: [35.8617, 104.1954],
    timezones: ['UTC+08:00'],
    borders: ['AFG', 'BTN', 'IND', 'KAZ', 'KGZ', 'LAO', 'MNG', 'MMR', 'NPL', 'PRK', 'RUS', 'TJK', 'VNM'],
  },
  {
    name: { common: 'India', official: 'Republic of India' },
    cca2: 'IN',
    cca3: 'IND',
    region: 'Asia',
    subregion: 'Southern Asia',
    capital: ['New Delhi'],
    area: 3287263,
    population: 1417173173,
    languages: { hin: 'Hindi', eng: 'English' },
    currencies: { INR: { name: 'Indian rupee', symbol: '₹' } },
    flags: { svg: '🇮🇳' },
    latlng: [20.5937, 78.9629],
    timezones: ['UTC+05:30'],
    borders: ['AFG', 'BGD', 'BTN', 'MMR', 'CHN', 'NPL', 'PAK', 'LKA'],
  },
  {
    name: { common: 'Germany', official: 'Federal Republic of Germany' },
    cca2: 'DE',
    cca3: 'DEU',
    region: 'Europe',
    subregion: 'Western Europe',
    capital: ['Berlin'],
    area: 357022,
    population: 84607016,
    languages: { deu: 'German' },
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    flags: { svg: '🇩🇪' },
    latlng: [51.1657, 10.4515],
    timezones: ['UTC+01:00'],
    borders: ['AUT', 'BEL', 'CZE', 'DNK', 'FRA', 'NLD', 'POL', 'CHE'],
  },
  {
    name: { common: 'France', official: 'French Republic' },
    cca2: 'FR',
    cca3: 'FRA',
    region: 'Europe',
    subregion: 'Western Europe',
    capital: ['Paris'],
    area: 643801,
    population: 67970571,
    languages: { fra: 'French' },
    currencies: { EUR: { name: 'Euro', symbol: '€' } },
    flags: { svg: '🇫🇷' },
    latlng: [46.2276, 2.2137],
    timezones: ['UTC+01:00'],
    borders: ['AND', 'BEL', 'DEU', 'ITA', 'LUX', 'MCO', 'ESP', 'CHE'],
  },
  {
    name: { common: 'Japan', official: 'Japan' },
    cca2: 'JP',
    cca3: 'JPN',
    region: 'Asia',
    subregion: 'Eastern Asia',
    capital: ['Tokyo'],
    area: 377975,
    population: 123294513,
    languages: { jpn: 'Japanese' },
    currencies: { JPY: { name: 'Japanese yen', symbol: '¥' } },
    flags: { svg: '🇯🇵' },
    latlng: [36.2048, 138.2529],
    timezones: ['UTC+09:00'],
    borders: [],
  },
  {
    name: { common: 'United Kingdom', official: 'United Kingdom of Great Britain and Northern Ireland' },
    cca2: 'GB',
    cca3: 'GBR',
    region: 'Europe',
    subregion: 'Northern Europe',
    capital: ['London'],
    area: 242900,
    population: 67736802,
    languages: { eng: 'English' },
    currencies: { GBP: { name: 'British pound', symbol: '£' } },
    flags: { svg: '🇬🇧' },
    latlng: [55.3781, -3.436],
    timezones: ['UTC+00:00'],
    borders: ['IRL'],
  },
  {
    name: { common: 'Russia', official: 'Russian Federation' },
    cca2: 'RU',
    cca3: 'RUS',
    region: 'Europe',
    subregion: 'Eastern Europe',
    capital: ['Moscow'],
    area: 17098246,
    population: 144444359,
    languages: { rus: 'Russian' },
    currencies: { RUB: { name: 'Russian ruble', symbol: '₽' } },
    flags: { svg: '🇷🇺' },
    latlng: [61.52401, 105.318756],
    timezones: ['UTC+02:00', 'UTC+03:00', 'UTC+04:00', 'UTC+05:00', 'UTC+06:00', 'UTC+07:00', 'UTC+08:00', 'UTC+09:00', 'UTC+10:00', 'UTC+11:00', 'UTC+12:00'],
    borders: ['AZE', 'BLR', 'CHN', 'EST', 'FIN', 'GEO', 'KAZ', 'PRK', 'LVA', 'LTU', 'MNG', 'NOR', 'POL', 'UKR'],
  },
  {
    name: { common: 'Australia', official: 'Commonwealth of Australia' },
    cca2: 'AU',
    cca3: 'AUS',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    capital: ['Canberra'],
    area: 7692024,
    population: 26068792,
    languages: { eng: 'English' },
    currencies: { AUD: { name: 'Australian dollar', symbol: '$' } },
    flags: { svg: '🇦🇺' },
    latlng: [-25.2744, 133.7751],
    timezones: ['UTC+05:00', 'UTC+06:30', 'UTC+07:00', 'UTC+08:00', 'UTC+08:45', 'UTC+09:00', 'UTC+09:30', 'UTC+10:00', 'UTC+10:30', 'UTC+11:00'],
    borders: [],
  },
];
