/**
 * GeoInsight — Dados Mock para Desenvolvimento
 * Dark Tech Sophisticated — Cyberpunk Minimalism
 * 
 * Dados de exemplo para testes quando a API está indisponível
 * Extraído da REST Countries API v5
 */

import { CountryData } from '@/types/countries';

export const mockCountries: CountryData[] = [
  {
    name: { common: 'Afghanistan', official: 'Afghanistan' },
    cca2: 'AF',
    cca3: 'AFG',
    region: 'Asia',
    subregion: 'Southern Asia',
    capital: [],
    area: 652230,
    population: 35000000,
    languages: { 'prs': 'Dari', 'ps': 'Pashto', 'tk': 'Turkmen' },
    currencies: { 'AFN': { name: 'Afghan afghani', symbol: '؋' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/af.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Albania', official: 'Albania' },
    cca2: 'AL',
    cca3: 'ALB',
    region: 'Europe',
    subregion: 'Southeast Europe',
    capital: [],
    area: 28748,
    population: 2402113,
    languages: { 'sq': 'Albanian' },
    currencies: { 'ALL': { name: 'Albanian lek', symbol: 'L' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/al.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Algeria', official: 'Algeria' },
    cca2: 'DZ',
    cca3: 'DZA',
    region: 'Africa',
    subregion: 'Northern Africa',
    capital: [],
    area: 2381741,
    population: 47400000,
    languages: { 'ar': 'Arabic' },
    currencies: { 'DZD': { name: 'Algerian dinar', symbol: 'د.ج' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/dz.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'American Samoa', official: 'American Samoa' },
    cca2: 'AS',
    cca3: 'ASM',
    region: 'Oceania',
    subregion: 'Polynesia',
    capital: [],
    area: 199,
    population: 43268,
    languages: { 'en': 'English', 'sm': 'Samoan' },
    currencies: { 'USD': { name: 'United States dollar', symbol: '$' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/as.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Andorra', official: 'Andorra' },
    cca2: 'AD',
    cca3: 'AND',
    region: 'Europe',
    subregion: 'Southern Europe',
    capital: [],
    area: 468,
    population: 89368,
    languages: { 'ca': 'Catalan' },
    currencies: { 'EUR': { name: 'Euro', symbol: '€' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/ad.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Angola', official: 'Angola' },
    cca2: 'AO',
    cca3: 'AGO',
    region: 'Africa',
    subregion: 'Middle Africa',
    capital: [],
    area: 1246700,
    population: 36604681,
    languages: { 'pt': 'Portuguese' },
    currencies: { 'AOA': { name: 'Angolan kwanza', symbol: 'Kz' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/ao.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Anguilla', official: 'Anguilla' },
    cca2: 'AI',
    cca3: 'AIA',
    region: 'Americas',
    subregion: 'Caribbean',
    capital: [],
    area: 91,
    population: 16010,
    languages: { 'en': 'English' },
    currencies: { 'XCD': { name: 'Eastern Caribbean dollar', symbol: '$' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/ai.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Antarctica', official: 'Antarctica' },
    cca2: 'AQ',
    cca3: 'ATA',
    region: 'Antarctic',
    subregion: '',
    capital: [],
    area: 14000000,
    population: 1300,
    languages: {  },
    currencies: {  },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/aq.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Antigua and Barbuda', official: 'Antigua and Barbuda' },
    cca2: 'AG',
    cca3: 'ATG',
    region: 'Americas',
    subregion: 'Caribbean',
    capital: [],
    area: 442,
    population: 106365,
    languages: { 'en': 'English' },
    currencies: { 'XCD': { name: 'Eastern Caribbean dollar', symbol: '$' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/ag.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Argentina', official: 'Argentina' },
    cca2: 'AR',
    cca3: 'ARG',
    region: 'Americas',
    subregion: 'South America',
    capital: [],
    area: 2780400,
    population: 46735004,
    languages: { 'gn': 'Guarani', 'es': 'Spanish' },
    currencies: { 'ARS': { name: 'Argentine peso', symbol: '$' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/ar.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Armenia', official: 'Armenia' },
    cca2: 'AM',
    cca3: 'ARM',
    region: 'Asia',
    subregion: 'Western Asia',
    capital: [],
    area: 29743,
    population: 3100100,
    languages: { 'hy': 'Armenian' },
    currencies: { 'AMD': { name: 'Armenian dram', symbol: '֏' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/am.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Aruba', official: 'Aruba' },
    cca2: 'AW',
    cca3: 'ABW',
    region: 'Americas',
    subregion: 'Caribbean',
    capital: [],
    area: 180,
    population: 108880,
    languages: { 'nl': 'Dutch', 'pap': 'Papiamento' },
    currencies: { 'AWG': { name: 'Aruban florin', symbol: 'ƒ' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/aw.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Australia', official: 'Australia' },
    cca2: 'AU',
    cca3: 'AUS',
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    capital: [],
    area: 7692024,
    population: 27724744,
    languages: { 'en': 'English' },
    currencies: { 'AUD': { name: 'Australian dollar', symbol: '$' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/au.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Austria', official: 'Austria' },
    cca2: 'AT',
    cca3: 'AUT',
    region: 'Europe',
    subregion: 'Central Europe',
    capital: [],
    area: 83871,
    population: 9219113,
    languages: { 'de': 'German' },
    currencies: { 'EUR': { name: 'Euro', symbol: '€' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/at.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Azerbaijan', official: 'Azerbaijan' },
    cca2: 'AZ',
    cca3: 'AZE',
    region: 'Asia',
    subregion: 'Western Asia',
    capital: [],
    area: 86600,
    population: 10353296,
    languages: { 'az': 'Azerbaijani' },
    currencies: { 'AZN': { name: 'Azerbaijani manat', symbol: '₼' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/az.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Bahamas', official: 'Bahamas' },
    cca2: 'BS',
    cca3: 'BHS',
    region: 'Americas',
    subregion: 'Caribbean',
    capital: [],
    area: 13943,
    population: 398165,
    languages: { 'en': 'English' },
    currencies: { 'BSD': { name: 'Bahamian dollar', symbol: '$' }, 'USD': { name: 'United States dollar', symbol: '$' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/bs.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Bahrain', official: 'Bahrain' },
    cca2: 'BH',
    cca3: 'BHR',
    region: 'Asia',
    subregion: 'Western Asia',
    capital: [],
    area: 765,
    population: 1501635,
    languages: { 'ar': 'Arabic' },
    currencies: { 'BHD': { name: 'Bahraini dinar', symbol: '.د.ب' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/bh.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Bangladesh', official: 'Bangladesh' },
    cca2: 'BD',
    cca3: 'BGD',
    region: 'Asia',
    subregion: 'Southern Asia',
    capital: [],
    area: 147570,
    population: 175423000,
    languages: { 'bn': 'Bengali' },
    currencies: { 'BDT': { name: 'Bangladeshi taka', symbol: '৳' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/bd.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Barbados', official: 'Barbados' },
    cca2: 'BB',
    cca3: 'BRB',
    region: 'Americas',
    subregion: 'Caribbean',
    capital: [],
    area: 430,
    population: 281998,
    languages: { 'en': 'English' },
    currencies: { 'BBD': { name: 'Barbadian dollar', symbol: '$' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/bb.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Belarus', official: 'Belarus' },
    cca2: 'BY',
    cca3: 'BLR',
    region: 'Europe',
    subregion: 'Eastern Europe',
    capital: [],
    area: 207600,
    population: 9109280,
    languages: { 'be': 'Belarusian', 'ru': 'Russian' },
    currencies: { 'BYN': { name: 'Belarusian ruble', symbol: 'Br' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/by.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Belgium', official: 'Belgium' },
    cca2: 'BE',
    cca3: 'BEL',
    region: 'Europe',
    subregion: 'Western Europe',
    capital: [],
    area: 30528,
    population: 11867634,
    languages: { 'de': 'German', 'fr': 'French', 'nl': 'Dutch' },
    currencies: { 'EUR': { name: 'Euro', symbol: '€' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/be.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Belize', official: 'Belize' },
    cca2: 'BZ',
    cca3: 'BLZ',
    region: 'Americas',
    subregion: 'Central America',
    capital: [],
    area: 22966,
    population: 397483,
    languages: { 'bjz': 'Belize Kriol', 'en': 'English', 'es': 'Spanish' },
    currencies: { 'BZD': { name: 'Belize dollar', symbol: '$' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/bz.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Benin', official: 'Benin' },
    cca2: 'BJ',
    cca3: 'BEN',
    region: 'Africa',
    subregion: 'Western Africa',
    capital: [],
    area: 112622,
    population: 13754688,
    languages: { 'fr': 'French' },
    currencies: { 'XOF': { name: 'West African CFA franc', symbol: 'Fr' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/bj.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
  {
    name: { common: 'Bermuda', official: 'Bermuda' },
    cca2: 'BM',
    cca3: 'BMU',
    region: 'Americas',
    subregion: 'North America',
    capital: [],
    area: 54,
    population: 63913,
    languages: { 'en': 'English' },
    currencies: { 'BMD': { name: 'Bermudian dollar', symbol: '$' } },
    flags: { svg: 'https://flags.restcountries.com/v5/svg/bm.svg' },
    latlng: undefined,
    timezones: [],
    borders: [],
  },
];
